### ISSUE TITLE
MAL Homepage Whitebar + Empty Gap

### ISSUE THREAD

**Issue by zacharyedwardsdowns** [cicerakes/DarkNight-MyAnimeList#1]
I am using Stylus to apply this style off of it's userstyle page. There is now an issue where there is a white bar at the top of the MAL homepage when using this style, as well as a gap between the title and menus. https://myanimelist.net/

![Screenshot from 2019-07-01 20-13-03](https://user-images.githubusercontent.com/39097461/60461061-5be23400-9c3d-11e9-9a9d-55cf198bb0aa.png)

I fixed this issue by adding these lines:
```
#myanimelist::before {
    content: none;
}

.ad-tag {
    margin-bottom: -18px;
}
```

**Comment by zacharyedwardsdowns** [comment]
Fix for the new homepage gradient background:

```
body:not(.ownlist):before {
    background: transparent;
}
```

**Comment by cicerakes** [comment]
I recommend switching over to the [UserCSS version](https://raw.githubusercontent.com/cicerakes/DarkNight-MyAnimeList/master/DarkNightMAL.user.css) if you haven't already, since the Userstyle version is outdated. 

I couldn't reproduce the white bar issue on either versions, but I'll add in your code since it doesn't cause issues. 
The background issue was temporary, but I'll also patch it to prevent future occurrences.
