### ISSUE TITLE
White parts in Studio page

### ISSUE THREAD

**Issue by along02** [cicerakes/DarkNight-MyAnimeList#5]
- **Browser:**  Google Chrome
- **Link to page where the issue occurs:** https://myanimelist.net/anime/producer/2/Kyoto_Animation

**Describe the problem**
There are white sections on the studio pages of MAL. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/21041802/148497892-99e21aef-4a44-4520-b1ed-d86b64d11d71.png)

**Comment by BriterNC** [comment]
@along02 I just have it fixed by adding these lines to code1 section:

> .seasonal-anime-list .seasonal-anime .properties .property, .seasonal-anime-list .seasonal-anime .properties .property:nth-child(even) {
    background-color: #1e1e1e;
}
.seasonal-anime-list .seasonal-anime .image {
    background-color: #1e1e1e;
}
.seasonal-anime-list .seasonal-anime .information {
    background-color: #2a2a2a;
}

Try it out if it's works or not. 😄 

**Screenshots:**

before
![image](https://user-images.githubusercontent.com/27994735/148510668-f2f7a9c8-f38b-479f-95f3-ef9f464bd9ca.png)
after
![image](https://user-images.githubusercontent.com/27994735/148510117-c4444d04-e46a-485f-87f0-5391e592bf7e.png)
